### ISSUE TITLE
请问在扩展那一直在转圈圈无法操作是什么情况

### ISSUE THREAD

**Issue by wenziren** [uparrows/tachidesk_cn#1]
请问在扩展那一直在转圈圈无法操作是什么情况

**Comment by uparrows** [comment]
需要全局科学上网，ssh链接到nas，ping下raw.githubusercontent.com，看看网络能否链接上githubusercontent

**Comment by Cr4w1er** [comment]
你好我也是跟他一样的问题，但是我已经按照你的方法用ssh连接到nas试过确认是连得上的，但是扩展那里也还是一直转圈

**Comment by uparrows** [comment]
> 你好我也是跟他一样的问题，但是我已经按照你的方法用ssh连接到nas试过确认是连得上的，但是扩展那里也还是一直转圈

除了网络问题，不会有其他问题得，转圈圈就是网络加载不出，需要将githubusercontent.com强制走代理。
看看有没有被dns污染到127.0.0.1：如图
![01](https://user-images.githubusercontent.com/38988286/181669569-765f54eb-9f61-4616-b515-7110f8367d75.jpg)
下面这种是正常情况：
![25482013e263dec6](https://user-images.githubusercontent.com/38988286/181669628-5e89de6d-7ea5-4582-974e-fce3d781b03e.png)
路由器上某插件建议这样设置：
![02](https://user-images.githubusercontent.com/38988286/181669837-6d5f75af-f4a6-4753-bb12-7a80e34d01c4.jpg)
![01](https://user-images.githubusercontent.com/38988286/181670218-269e1abc-b3aa-4128-a1d9-93404c160129.jpg)
![02](https://user-images.githubusercontent.com/38988286/181670228-3b96dc08-7649-4166-96f1-3b5edc763c97.jpg)
![03](https://user-images.githubusercontent.com/38988286/181670373-a36112a0-03fb-487c-be56-49c34a5c2677.jpg)
![04](https://user-images.githubusercontent.com/38988286/181670417-3613d758-0fce-405f-8008-9beb7100cad1.jpg)

**Comment by KZMsatoru** [comment]
人肉翻墙，也是一样转圈圈
PuTTY里面是正常的
![QQ截图20231216120802](https://github.com/uparrows/tachidesk_cn/assets/64807117/d22928f5-7f4d-4166-9514-7575b843fb6f)

**Comment by w0000dy** [comment]
一样的情况 NAS可ping通raw.githubusercontent.com 但是插件就是转圈圈
