### ISSUE TITLE
感谢分享，up可以放一个docke-compose文件，小白操作更简单

### ISSUE THREAD

**Issue by coeoe** [uparrows/tachidesk_cn#2]
<details>
<summary>docker-compose.yml</summary>

```version: "3"
services:
  tachidesk_cn:
    image: dezhao/tachidesk_cn
    container_name: tachidesk_cn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - 本地路径:/root/.local/share/Tachidesk  #将“本地路径”替换为在设备建立的文件夹路径
    ports:
      - 1234:4567 #端口根据自己需求更改“1234”
    restart: always
```
</details>

**Comment by uparrows** [comment]
> docker-compose.yml
> ```
> services:
>   tachidesk_cn:
>     image: dezhao/tachidesk_cn
>     container_name: tachidesk_cn
>     environment:
>       - PUID=1000
>       - PGID=1000
>       - TZ=Asia/Shanghai
>     volumes:
>       - 本地路径:/root/.local/share/Tachidesk  #将“本地路径”替换为在设备建立的文件夹路径
>     ports:
>       - 1234:4567 #端口根据自己需求更改“1234”
>     restart: always
> ```

安排😁
