### ISSUE TITLE
修改配置文件不生效

### ISSUE THREAD

**Issue by Kelcoin** [uparrows/tachidesk_cn#3]
我尝试编辑了/root/.local/share/Tachidesk和/root/Tachidesk目录下的server.conf文件
我更改的选项均不会生效
请问是什么原因

这是修改前的conf

> **# Server ip and port bindings**
> server.ip = "0.0.0.0"
> server.port = 4567
> 
> **# Socks5 proxy**
> server.socksProxyEnabled = false
> server.socksProxyHost = ""
> server.socksProxyPort = ""
> 
> **# Authentication**
> server.basicAuthEnabled = false
> server.basicAuthUsername = ""
> server.basicAuthPassword = "" 
>
> **# webUI**
> server.webUIEnabled = true
> server.webUIFlavor = "WebUI" # "WebUI" or "Sorayomi" or "Custom"
> server.initialOpenInBrowserEnabled = true
> server.webUIInterface = "browser" # "browser" or "electron"
> server.electronPath = ""
> 
> **# misc**
> server.debugLogsEnabled = false
> server.systemTrayEnabled = true
> server.downloadsPath = ""

这是修改后的conf

> **# Server ip and port bindings**
> server.ip = "0.0.0.0"
> server.port = 4567
> 
> **# Socks5 proxy**
> server.socksProxyEnabled = false
> server.socksProxyHost = ""
> server.socksProxyPort = ""
> 
> **# webUI**
> server.webUIEnabled = true
> server.webUIFlavor = "WebUI" # "WebUI" or "Sorayomi" or "Custom"
> server.initialOpenInBrowserEnabled = true
> server.webUIInterface = "browser" # "browser" or "electron"
> server.electronPath = ""
> 
> **# Authentication**
> server.basicAuthEnabled = true
> server.basicAuthUsername = "user"
> server.basicAuthPassword = "password" 
> 
> **# misc**
> server.debugLogsEnabled = false
> server.systemTrayEnabled = true
> server.downloadsPath = ""

日志

> text  error  warn  system  array  login  
> 
>         "electronPath" : "",
>         "initialOpenInBrowserEnabled" : true,
>         "ip" : "0.0.0.0",
>         "port" : 4567,
>         "socksProxyEnabled" : false,
>         "socksProxyHost" : "",
>         "socksProxyPort" : "",
>         "systemTrayEnabled" : true,
>         "webUIEnabled" : true,
>         "webUIFlavor" : "WebUI",
> java.io.IOException: Current OS and desktop configuration does not support `browseURL`
>         at dorkbox.util.Desktop.browseURL(Desktop.java:154)
>         at dorkbox.util.Desktop.browseURL(Desktop.java:115)
>         at suwayomi.tachidesk.server.util.Browser.openInBrowser(Browser.kt:30)
>         at suwayomi.tachidesk.server.JavalinSetup.javalinSetup$lambda-3$lambda-2(JavalinSetup.kt:74)
>         "webUIInterface" : "browser"    at io.javalin.core.event.EventManager.fireEvent(EventManager.kt:18)
> 
>         at io.javalin.Javalin.start(Javalin.java:177)
>         at io.javalin.Javalin.start(Javalin.java:149)
>         at io.javalin.Javalin.start(Javalin.java:135)
>         at suwayomi.tachidesk.server.JavalinSetup.javalinSetup(JavalinSetup.kt:77)
>         at suwayomi.tachidesk.MainKt.main(Main.kt:15)
>     }   at suwayomi.tachidesk.MainKt.main(Main.kt)
> 
> }
> 
> 05:27:43.749 [main] DEBUG suwayomi.tachidesk.server.ServerSetup - Data Root directory is set to: /root/.local/share/Tachidesk
> 05:27:44.120 [main] INFO  suwayomi.tachidesk.server.util.AppMutex - Mutex status is clear, Resuming startup.
> 05:27:44.477 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - found Migration class suwayomi.tachidesk.server.database.migration.M0019_RemoveAnime
> 05:27:44.498 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - found Migration class suwayomi.tachidesk.server.database.migration.M0018_MangaInLibraryAt
> 05:27:44.499 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - found Migration class suwayomi.tachidesk.server.database.migration.M0017_ChapterFetchedAt
> 05:27:44.499 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - found Migration class suwayomi.tachidesk.server.database.migration.M0016_ChapterIndexRenameToSourceOrder
> 05:27:44.500 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - found Migration class suwayomi.tachidesk.server.database.migration.M0015_SourceAndExtensionLangAddLengthLimit
> 05:27:44.500 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - found Migration class suwayomi.tachidesk.server.database.migration.M0014_MangaRemoveLengthLimit
> 05:27:44.500 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - found Migration class suwayomi.tachidesk.server.database.migration.M0013_MangaRealUrl
> 05:27:44.500 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - found Migration class suwayomi.tachidesk.server.database.migration.M0012_SourceIsNsfw
> 05:27:44.501 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - found Migration class suwayomi.tachidesk.server.database.migration.M0011_SourceDropPartOfFactorySource
> 05:27:44.501 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - found Migration class suwayomi.tachidesk.server.database.migration.M0010_MangaAndChapterMeta
> 05:27:44.502 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - found Migration class suwayomi.tachidesk.server.database.migration.M0009_ChapterLastReadAt
> 05:27:44.502 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - found Migration class suwayomi.tachidesk.server.database.migration.M0008_ChapterPageCount
> 05:27:44.503 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - found Migration class suwayomi.tachidesk.server.database.migration.M0007_ChapterIsDownloaded
> 05:27:44.504 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - found Migration class suwayomi.tachidesk.server.database.migration.M0006_AnimeTablesBatch3
> 05:27:44.504 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - found Migration class suwayomi.tachidesk.server.database.migration.M0005_AnimeTablesBatch2
> 05:27:44.504 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - found Migration class suwayomi.tachidesk.server.database.migration.M0004_AnimeTablesBatch1
> 05:27:44.504 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - found Migration class suwayomi.tachidesk.server.database.migration.M0003_DefaultCategory
> 05:27:44.506 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - found Migration class suwayomi.tachidesk.server.database.migration.M0002_ChapterTableIndexRename
> 05:27:44.507 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - found Migration class suwayomi.tachidesk.server.database.migration.M0001_Initial
> 05:27:44.893 [main] INFO  de.neonew.exposed.migrations.RunMigrations - Running migrations on database jdbc:h2:/root/.local/share/Tachidesk/database
> 05:27:45.446 [main] INFO  de.neonew.exposed.migrations.RunMigrations - Database version before migrations: 19
> 05:27:45.446 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - Skipping migration version 1: Initial
> 05:27:45.447 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - Skipping migration version 2: ChapterTableIndexRename
> 05:27:45.447 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - Skipping migration version 3: DefaultCategory
> 05:27:45.447 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - Skipping migration version 4: AnimeTablesBatch1
> 05:27:45.447 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - Skipping migration version 5: AnimeTablesBatch2
> 05:27:45.447 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - Skipping migration version 6: AnimeTablesBatch3
> 05:27:45.447 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - Skipping migration version 7: ChapterIsDownloaded
> 05:27:45.447 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - Skipping migration version 8: ChapterPageCount
> 05:27:45.447 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - Skipping migration version 9: ChapterLastReadAt
> 05:27:45.447 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - Skipping migration version 10: MangaAndChapterMeta
> 05:27:45.447 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - Skipping migration version 11: SourceDropPartOfFactorySource
> 05:27:45.447 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - Skipping migration version 12: SourceIsNsfw
> 05:27:45.447 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - Skipping migration version 13: MangaRealUrl
> 05:27:45.447 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - Skipping migration version 14: MangaRemoveLengthLimit
> 05:27:45.447 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - Skipping migration version 15: SourceAndExtensionLangAddLengthLimit
> 05:27:45.447 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - Skipping migration version 16: ChapterIndexRenameToSourceOrder
> 05:27:45.447 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - Skipping migration version 17: ChapterFetchedAt
> 05:27:45.447 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - Skipping migration version 18: MangaInLibraryAt
> 05:27:45.447 [main] DEBUG de.neonew.exposed.migrations.RunMigrations - Skipping migration version 19: RemoveAnime
> 05:27:45.447 [main] INFO  de.neonew.exposed.migrations.RunMigrations - Migrations finished successfully
> 05:27:45.862 [main] ERROR dorkbox.systemTray.SystemTray - Cannot use the SystemTray in a headless environment
> 05:27:46.076 [main] INFO  suwayomi.tachidesk.server.util.WebInterfaceManager - WebUI Static files exists and is the correct revision
> 05:27:46.077 [main] INFO  suwayomi.tachidesk.server.util.WebInterfaceManager - Verifying WebUI Static files...
> 05:27:46.281 [main] INFO  suwayomi.tachidesk.server.util.WebInterfaceManager - md5: 93ac86678bda8ae57a05eebddc2e6034
> 05:27:46.282 [main] INFO  suwayomi.tachidesk.server.JavalinSetup - Serving web static files for WebUI
> 05:27:46.347 [main] INFO  io.javalin.Javalin - Static file handler added: StaticFileConfig(hostedPath=/, directory=/root/.local/share/Tachidesk/webUI, location=EXTERNAL, precompress=false, aliasCheck=null, headers={Cache-Control=max-age=0}, skipFileFunction=(javax.servlet.http.HttpServletRequest) -> kotlin.Boolean). File system location: '/root/.local/share/Tachidesk/webUI'
> 05:27:46.378 [main] WARN  io.javalin.Javalin - Kotlin 1.5 has a breaking change to reflection - the OpenAPI plugin will not work properly. Please visit https://github.com/tipsy/javalin/issues/1193 if you want to help fix this issue.
> 05:27:46.396 [main] INFO  io.javalin.Javalin - Static file handler added: StaticFileConfig(hostedPath=/, directory=META-INF/resources/webjars, location=CLASSPATH, precompress=false, aliasCheck=null, headers={Cache-Control=max-age=31622400}, skipFileFunction=(javax.servlet.http.HttpServletRequest) -> kotlin.Boolean). File system location: 'jar:file:/root/Tachidesk/Tachidesk-Server-cn-by-dezhao.jar!/META-INF/resources/webjars'
> 05:27:46.401 [main] INFO  io.javalin.Javalin - 
>        __                      __ _            __ __
>       / /____ _ _   __ ____ _ / /(_)____      / // /
>  __  / // __ `/| | / // __ `// // // __ \    / // /_
> / /_/ // /_/ / | |/ // /_/ // // // / / /   /__  __/
> \____/ \__,_/  |___/ \__,_//_//_//_/ /_/      /_/
> 
>           https://javalin.io/documentation
> 
> 05:27:46.401 [main] INFO  io.javalin.Javalin - Starting Javalin ...
> 05:27:46.413 [main] INFO  io.javalin.Javalin - You are running Javalin 4.2.0 (released January 2, 2022. Your Javalin version is 216 days old. Consider checking for a newer version.).
> 05:27:46.639 [main] INFO  io.javalin.Javalin - Listening on http://0.0.0.0:4567/
> 05:27:46.640 [main] INFO  io.javalin.Javalin - Javalin started in 239ms \o/

**Comment by uparrows** [comment]
测试多次，修改之后重启容器生效，/root/.local/share/Tachidesk是挂载到nas上的文件夹的
![888888888888888](https://user-images.githubusercontent.com/38988286/183431418-fa2aee4b-a983-4763-8178-6fe1e6d95a51.jpg)
![66666666](https://user-images.githubusercontent.com/38988286/183431451-98c92d14-83c1-4e58-8566-a837de3e697c.jpg)

**Comment by uparrows** [comment]
修改配置文件后必须重启容器才生效，/root/.local/share/Tachidesk是挂载到nas上的文件夹的，修改对应nas挂载文件夹的conf文件
