### ISSUE TITLE
The Chinese translation 

### ISSUE THREAD

**Issue by AriaMoradi** [uparrows/tachidesk_cn#4]
Hey, I'm the main developer of Tachidesk, looks like you have done a great job translating the app.
Can you honor the open source license and share source code of your work?

**Comment by uparrows** [comment]
> Hey, I'm the main developer of Tachidesk, looks like you have done a great job translating the app. Can you honor the open source license and share source code of your work?

of course yes , I will share the source code after I finish the translation of the new version ，is there any plan to support multiple languages?  maybe i can be of some help .

**Comment by AriaMoradi** [comment]
If there's demand, we can add a i18n solution to Tachidesk-WebUI. You could add your translations then.

**Comment by AriaMoradi** [comment]
I'll work on a weblate based solution soon

**Comment by uparrows** [comment]
> I'll work on a weblate based solution soon
translated source code here : https://github.com/uparrows/Tachidesk-WebUI-CN
